[project]
authors = [{ name = "Geoff Boeing", email = "boeing@usc.edu" }]
dependencies = [
    "folium",
    "geopandas",
    "jupyterlab",
    "mapclassify",
    "matplotlib",
    "nbdime",
    "networkx",
    "numpy",
    "osmnx==2.0.4",
    "pandas",
    "pre-commit",
    "python-igraph",
    "rasterio",
    "requests",
    "rio-vrt",
    "scikit-learn",
    "scipy",
    "shapely",
]
description = "Gallery of OSMnx tutorials, usage examples, and feature demonstations."
license = "MIT"
license-files = ["LICENSE.txt"]
name = "osmnx-examples"
readme = "README.md"
requires-python = ">=3.9"
version = "2.0.4"

[tool.ruff]
cache-dir = "~/.cache/pre-commit/ruff"
line-length = 100

[tool.ruff.lint]
extend-select = ["A", "B", "E", "F", "I", "UP", "W"]

[tool.ruff.lint.pycodestyle]
max-line-length = 110 # line length + 10% since it isn't a hard upper bound
